### ISSUE TITLE
Why is there no pull request in QMK for Anne Pro 2?

### ISSUE THREAD

**Issue by MycroftHolmes1989** [OpenAnnePro/AnnePro2-Tools#10]
Is there any conflicts or incompatibilities that will block merge of Anne Pro 2 with QMK?

**Comment by Codetector1374** [comment]
What do you mean? Merge with upstream the main QMK/Qmk_firmware repo?

**Comment by MycroftHolmes1989** [comment]
Yes

**Comment by Codetector1374** [comment]
Okay sorry for putting this off for a few days. 

We sort of have plans of doing this. But it would require

1.  QMK Adopts the new ChibiOS-Contrib update that is currently already merged in Chibios/Chibios-Contrib
2. QMK Adopts the new ChibiOS 20.x branch. Which I heard is happening sometime this year (2021)
3. Figuring out what are we going to do wrt. Shine. Since we might need the two ver to match up, with QMK in the main repo, we won't have control over when PRs happen etc.

**Comment by MycroftHolmes1989** [comment]
Okay, good to know.

As an aside, I would request you to enable the issue section for the QMK fork, because I think there are bugs in the fork.

**Comment by Codetector1374** [comment]
okay done
